### ISSUE TITLE
Window size exception

### ISSUE THREAD

**Issue by hazardousmedic** [EtiTheSpirit/BNKReplacer#2]
![RepackerError](https://user-images.githubusercontent.com/20057445/87046765-92934880-c1c7-11ea-87d9-d914f939c658.jpg)

Receiving this error whether run via command line or direct opening the exe, unable to get past it.

**Comment by EtiTheSpirit** [comment]
I think this has to do with the powershell window. For now, could you try running it in cmd instead of powershell? That should ideally work better until I get a fix out.

**Comment by EtiTheSpirit** [comment]
After 10,000 years in development, hopefully it will have been worth the wait.
