### ISSUE TITLE
i need help i am dont know how to use a python script 

### ISSUE THREAD

**Issue by brahim065** [EtiTheSpirit/BNKReplacer#5]
Bro that python script that give you bnk ids i click on it but it opens for a second than it close why Can you help note: i installed python 3.8.6

**Comment by EtiTheSpirit** [comment]
This issue is unrelated to BNKReplacer. As much as I wish I could help, I simply don't know -- I don't deal with python. Try asking on the page where you downloaded the tool from instead.
