### ISSUE TITLE
NMSBankRepacker.exe crash: The value must be less than the console's current maximum window size...

### ISSUE THREAD

**Issue by Sophira** [EtiTheSpirit/BNKReplacer#9]
Firstly, thank you very much for this tool! It works really well for audio modding in No Man's Sky.

However, I have a problem; it seems to be *very* dependent on the console window size. It wants to open a 160x60 console window (with a buffer size of 160x300), and as far as I can tell, it cannot do that on my screen settings (1920x1080 at 125% scaling). When I try to do so, I get this error:

```
Shit hit the fan! A critical exception was thrown. Here's the error: The value must be less than the console's current maximum window size of 48 in that dimension. Note that this value depends on screen resolution and the console font.
Parameter name: height
Actual value was 60.
   at System.Console.SetWindowSize(Int32 width, Int32 height)
   at NMSBnkRepacker.Repacker.Main(String[] args)
Press enter to quit...
```

I also cannot use this program from the command line. When I try, I get a subtly different error - even if I'm in the same directory as the executable and running it without any arguments (so it should be exactly the same as double-clicking it):

```
D:\_linux-access\nms\BNKRepacker>NMSBnkRepacker.exe
Shit hit the fan! A critical exception was thrown. Here's the error: The value must be less than the console's current maximum window size of 147 in that dimension. Note that this value depends on screen resolution and the console font.
Parameter name: width
Actual value was 160.
   at System.Console.SetWindowSize(Int32 width, Int32 height)
   at NMSBnkRepacker.Repacker.Main(String[] args)
Press enter to quit...
```

Currently, the only way I am able to run the program is by reducing my scaling level to 100% and double-clicking the program (rather than using it via the command line), thus allowing it to open its own console window with different settings. However, this makes the output of the program difficult to read for me, especially as it seems that it uses a smaller console font size than my default.

I would like to be able to use this program in an automated fashion for creating a mod, but this issue makes that impossible (or at the least, difficult) currently, as far as I can tell.

Thank you again for making this tool!

**Comment by Sophira** [comment]
I just noticed issue #2, sorry! For the record, I am already using this via `cmd.exe` and not PowerShell.

I apologise for the duplicate - I'll leave it up to you whether to close this or not.

**Comment by EtiTheSpirit** [comment]
I got this fixed in the new release, it's the laziest possible fix I could have mustered but it should work.
